-- Persistent queries
CREATE TABLE YOUTUBE_CHANGES WITH (CLEANUP_POLICY='compact', KAFKA_TOPIC='youtube_changes', PARTITIONS=1, REPLICAS=3, RETENTION_MS=604800000) AS SELECT
  YOUTUBE_VIDEOS.VIDEO_ID VIDEO_ID,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.TITLE) TITLE,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.COMMENTS, 2)[1] COMMENTS_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.COMMENTS, 2)[2] COMMENTS_CURRENT,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.VIEWS, 2)[1] VIEWS_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.VIEWS, 2)[2] VIEWS_CURRENT,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.LIKES, 2)[1] LIKES_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.LIKES, 2)[2] LIKES_CURRENT
FROM YOUTUBE_VIDEOS YOUTUBE_VIDEOS
GROUP BY YOUTUBE_VIDEOS.VIDEO_ID
EMIT CHANGES;