-- Persistent queries
CREATE TABLE YOUTUBE_CHANGES WITH (CLEANUP_POLICY='compact', KAFKA_TOPIC='youtube_changes', PARTITIONS=1, REPLICAS=3, RETENTION_MS=604800000) AS SELECT
  YOUTUBE_VIDEOS.VIDEO_ID VIDEO_ID,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.TITLE) TITLE,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.COMMENTS, 2)[1] COMMENTS_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.COMMENTS, 2)[2] COMMENTS_CURRENT,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.VIEWS, 2)[1] VIEWS_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.VIEWS, 2)[2] VIEWS_CURRENT,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.LIKES, 2)[1] LIKES_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.LIKES, 2)[2] LIKES_CURRENT
FROM YOUTUBE_VIDEOS YOUTUBE_VIDEOS
GROUP BY YOUTUBE_VIDEOS.VIDEO_ID
EMIT CHANGES;


INSERT INTO telegram_outbox
SELECT
'5617219492' AS `chat_id`,
CONCAT(
  'Likes changed: ',
  CAST(likes_previous AS STRING),
  ' to ',
  CAST(likes_current AS STRING),
  ' in ',
  title
) AS `text`
FROM YOUTUBE_CHANGES_STREAM
WHERE likes_current <> likes_previous;

-- Stream Creation
CREATE STREAM youtube_changes_stream WITH (KAFKA_TOPIC = 'youtube_changes', VALUE_FORMAT='avro');


-- Check queries
INSERT INTO telegram_outbox (`chat_id`, `text`) 
VALUES ("$telegram's conversation id", 'Starting a Conversation by Code');
